# Generated by Django 4.1.4 on 2022-12-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title of video')),
                ('description', models.TextField(verbose_name='Description of video')),
                ('published_on', models.DateTimeField(verbose_name=' video publishing datetime')),
                ('thumb_url', models.URLField(max_length=255, verbose_name='Thumbnail URL')),
                ('video_link', models.URLField(max_length=255, verbose_name='Video Link')),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
    ]
